### ISSUE TITLE
Fix extract subcommand name in the doc

### ISSUE THREAD

**Issue by number492** [corneliusweig/konfig#11]
The documentation talks about an extract subcommand, even in the command line examples, while the current name of the subcommand is export.

**Comment by corneliusweig** [comment]
Oh yes. Thanks for your keen eyes. Do you want to take a stab at this?

Please also have a look at https://github.com/corneliusweig/konfig/blob/master/CONTRIBUTING.md#pull-request-checklist.

**Comment by corneliusweig** [comment]
Ok, it's fixed now. Thanks for reporting!
