### ISSUE TITLE
split fails: error: write /dev/stdout: permission denied

### ISSUE THREAD

**Issue by jglick** [corneliusweig/konfig#14]
```console
$ kubectl konfig split microk8s
error: write /dev/stdout: permission denied
```

Linux. `kubectl` 1.17.3 from Snap. Plugin v0.2.2.

**Comment by corneliusweig** [comment]
Hmm.. curious. Can you `export NDEBUG=y` and show the log output?
It could very well be a snap problem which I won't be able to reproduce, so if you want to investigate further that would be great.

**Comment by jglick** [comment]
> Can you `export NDEBUG=y` and show the log output?

Does not produce any additional output.

> It could very well be a snap problem

Indeed it seems that way—works when using a manually downloaded `kubectl`. This snap uses “classic confinement”, which generally means it should behave like a plain package (I have not encountered any permission-related errors in any other usage), but maybe there is some subtle difference here.

**Comment by Routhinator** [comment]
Also seeing this with the snap version of kubectl.

**Comment by corneliusweig** [comment]
This is a snap problem. There's nothing I can do to `konfig` to improve this situation.
FWIW, this seems related: https://github.com/moby/moby/issues/31243#issuecomment-406879017

**Comment by jglick** [comment]
What code here is actually trying to use `/dev/stdout`? I do not see any in this repo. Is it something being called _by_ this script? Most uses of `/dev/stdout` can be replaced (a bit awkwardly) with temp files.

**Comment by guettli** [comment]
this could be related to an issue of `snap`: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1849753

**Comment by jglick** [comment]
Indeed. https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1849753/comments/26 suggests a workaround: replace

```bash
kubectl … > "$tmpcfg"
```

with the rather cryptic

```bash
kubectl … > >(cat > "$tmpcfg")
```
