### ISSUE TITLE
Not compatible with Windows error

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [corneliusweig/konfig#17]
I am installing the plugin via `krew` and when I try `kubectl konfig help` I get the following error when running from cmd or powershell
```
fork/exec C:\Users\<username>\.krew\bin\kubectl-konfig.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```
I tried gitbash, but same issue happens if I run using `kubectl konfig` but it works if I run the exe directly.

**Comment by corneliusweig** [comment]
Sorry for the sluggish response. What version of `kubectl` are you running? AFAIR, there was a bug which broke all kubectl plugins before 1.15 (also see https://github.com/kubernetes-sigs/krew/issues/557).

**Comment by SayakMukhopadhyay** [comment]
The kubectl client version I am using is 1.17.1. Also, unfortunately I dont have another system to test this on so I am not sure if this is a misconfiguration of some sort.

**Comment by SayakMukhopadhyay** [comment]
Moreover, I am able to run other krew plugins (which are available on Windows)

**Comment by corneliusweig** [comment]
Thanks for trying again! I have to admit that I never had the chance to test this on Windows, so I'm very keen on getting it to work.

I found this issue in krew: https://github.com/kubernetes-sigs/krew/issues/131#issuecomment-522793797
It's most likely because krew installs the executable with an `.exe` extension. If you have capacity to do some debugging, it would be really helpful if you can get it to work. According to https://golang.org/src/os/exec/lp_windows.go, you can try no extra extension, or `.com`, `.bat`, `.cmd`. `LookPath` is called from here https://github.com/kubernetes/kubernetes/blob/14559bc4067ab5e41163986b5fa6f35cae9616ff/pkg/kubectl/cmd/cmd.go#L359 in `kubectl`.

**Comment by corneliusweig** [comment]
Maybe some more details: Krew adds a symlink in `$HOME/.krew/bin` folder, which points to the executable in `$HOME/.krew/store/konfig/v0.2.2/konfig-krew.exe`. It's the latter whose extension you need to change, but then you also need to adapt the symlink of `.krew/.bin/kubectl-konfig.exe` -> file with new ending.

**Comment by SayakMukhopadhyay** [comment]
Well, it seems like things are as expected then
![image](https://user-images.githubusercontent.com/13748882/83978493-74ff6480-a925-11ea-803a-af38560fe6d3.png)
![image](https://user-images.githubusercontent.com/13748882/83978501-834d8080-a925-11ea-943e-d9fc0415c680.png)

Moreover I can open the `konfig-krew.exe` file using VSCode and it has a bash script. Can Windows run a bash script disguised as an exe?

**Comment by corneliusweig** [comment]
Well apparently, that's not the case :worried:
It might work with a `.bat` extension. Can you try that?

**Comment by SayakMukhopadhyay** [comment]
Nope, turning it into a `.bat` doesn't work either. I must say that it doesn't work on powershell or command prompt. If I start the `kubectl-konfig.exe` from a bash shell like MINGW, it works but if I do `kubectl konfig <anything>` in that bash shell, I get the same error as in the OP.

**Comment by corneliusweig** [comment]
Ok, thank you a lot. I'm afraid this means that I'll have to abandon the windows distribution.

**Comment by SayakMukhopadhyay** [comment]
Do note that this could work in WSL, haven't tested. That said, ref. to the https://github.com/kubernetes-sigs/krew/issues/131#issuecomment-522793797
> That said, since we add .exe to every executable, if your plugin is actually not a win32 application, it will not work. For example, plugins that have a .ps1 or .bat extension currently don't work on Krew.

Since a bash script is not a Win32 application, it won't work. Do you know if powershell scripts work in krew or not? I could try and create a powershell alternative for this plugin.

**Comment by corneliusweig** [comment]
@SayakMukhopadhyay Thanks for offering your help. At the moment this does not make sense, though. `Krew` adds the `.exe` suffix to every plugin binary it installs (to the symlink, to be precise). I think the first step must be to come up with a way how `krew` could determine, which suffix is the right one. https://github.com/kubernetes-sigs/krew/issues/131#issuecomment-522793797 describes this problem in more detail.
So if you have the capacity, fixing that would be awesome! If you plan to go ahead, best open an issue in krew to discuss this.
