### ISSUE TITLE
Importing a config from a file without permission causes loss of ~/.kube/config content

### ISSUE THREAD

**Issue by Ancitik** [corneliusweig/konfig#26]
Hello everyone,

I was trying to import the kubeconfig from /etc/rancher/k3s/k3s.yaml to my ~/.kube/config.

Unfortunately /etc/rancher/k3s/k3s.yaml was in 600 so I could not read it. Konfig edited my ~/.kube/config and had empty it.

My KUBECONFIG is now empty and I lost my access to clusters I had.

```
➜ kubectl konfig import -s /etc/rancher/k3s/k3s.yaml
error: error loading config file "/etc/rancher/k3s/k3s.yaml": open /etc/rancher/k3s/k3s.yaml: permission denied 
```

Is that a miss-usage from me ?
Regards.

**Comment by corneliusweig** [comment]
No this is bad. Apparently, errors in the critical section are not handled properly and nobody has hit that bug so far. I'm sorry for causing you trouble.

#27 has a fix which I'll release asap.
