### ISSUE TITLE
Error importing kubeconfig files with "--" in its name

### ISSUE THREAD

**Issue by sTb1337** [corneliusweig/konfig#35]
I tried to import an kubeconfig file "kubeconfig--xxx-xxx--xxx-x.yaml"  but encountered the following error:

```
konfig import "kubeconfig--xxx-xxx--xxx-x.yaml"                                                                                                                                                             
error: unrecognized flag "kubeconfig--xxx-xxx--xxx-x.yaml"
```

**Comment by sTb1337** [comment]
i also tried without .yaml and removed "--".

```
konfig import kubeconfig-xxx-xxx-xxx-xxx                                                                                                                                                                          error: unrecognized flag "kubeconfig-xxx-xxx-xxx-xxx"

~/Downloads » konfig import kubeconfig-xxx-xxx-xxx-xxx --save                                                                                                                                                                   error: unrecognized flag "kubeconfig-xxx-xxx-xxx-xxx"
```

**Comment by corneliusweig** [comment]
Hm, I tried to repro your problem, but for me it worked fine. Can you please `export DEBUG=1` in your shell, run the command again, and paste the output here?

**Comment by sTb1337** [comment]
I would guess that [Line 74](https://github.com/corneliusweig/konfig/blob/master/konfig#L74)  is breaking execution. 

I think If you remove `"$1" =~ ^-(.*)`  it should work. Hopefully this helps, I am not that good with bash scripting.

**Comment by corneliusweig** [comment]
What's strange is that your output says `[[ kubeconfig--test-dsc5 =~ -(.*) ]]`, however the pattern in l.74 says `[[ "$1" =~ ^-(.*) ]]`. So the debug output shows matching against `-(.*)` but the code wants `^-(.*)`.
I don't know why the `^` gets lost. Can you tell me about your OS and bash version? However since I can't reproduce the problem I have to defer bug hunting to you.

**Comment by sTb1337** [comment]
After updating to v0.2.6 it worked.

```
konfig import kubeconfig--test-dsc5.yaml                                                                                                                                                                                       I540484@sTb31337
+ set -eEuo pipefail
+ TMPFILES=()
+ declare -a TMPFILES
+ trap cleanup EXIT
+ main import kubeconfig--test-dsc5.yaml
+ hash kubectl
+ KUBECTL=kubectl
+ [[ 2 -eq 0 ]]
+ case "$1" in
+ import_ctx kubeconfig--test-dsc5.yaml
+ tmpcfgs=()
+ declare -a tmpcfgs
+ local tmpcfg
+ local tmpinputcfg=
+ local out=
+ local arg=
++ mktemp konfig_XXXXXX
+ tmpcfg=konfig_sEV23k
+ TMPFILES+=("$tmpcfg")
+ tmpcfgs+=("$tmpcfg")
+ for OPT in "$@"
+ case $OPT in
+ kubectl config view --raw
+ [[ -z '' ]]
+ merge '' konfig_sEV23k kubeconfig--test-dsc5.yaml
+ [[ '' =~ ^-.+ ]]
+ IFS=':
	'
+ [[ '' == \-\p ]]
+ [[ '' == \-\-\p\r\e\s\e\r\v\e\-\s\t\r\u\c\t\u\r\e ]]
+ KUBECONFIG=:konfig_sEV23k:kubeconfig--test-dsc5.yaml
+ kubectl config view --flatten --merge
apiVersion: v1
clusters:
- cluster:
...
- name: user-read-only
  user: {}
+ IFS='
'
+ cleanup
+ [[ 1 -gt 0 ]]
+ rm -- konfig_sEV23k
```

I guess I had an old version of crew installed.

You may close the issue. Thanks a lot.

**Comment by corneliusweig** [comment]
> It would be helpful to keep the setup instructions of readme.md up to date or switch to an dynamic approach.

That sounds like a documentation bug. Can you tell me what exactly confused you? You can also send a PR :)

**Comment by sTb1337** [comment]
I will send an PR :) Thanks again for this great tool and your support :)

**Comment by sTb1337** [comment]
See https://github.com/corneliusweig/konfig/pull/39 :)
