### ISSUE TITLE
can't import konfig anymore

### ISSUE THREAD

**Issue by chukynax** [corneliusweig/konfig#37]
k konfig import -s config.yaml
error: write /dev/stdout: permission denied

**Comment by sTb1337** [comment]
What is your konfig and kubectl version?

Can you please export DEBUG=1 in your shell, run the command again, and paste the output here?

**Comment by corneliusweig** [comment]
This came up before and seems to be a problem with `snap`. I don't think there's anything I can do in `konfig` to change that.

See https://github.com/corneliusweig/konfig/issues/14#issuecomment-636793339
