### ISSUE TITLE
Plugin installed with krew gets a permission denied error to write to /dev/stdout

### ISSUE THREAD

**Issue by Bjohnson131** [corneliusweig/konfig#41]
https://github.com/corneliusweig/konfig/issues/37
The above issue is similar to mine, except instead of installing with snap, I'm installing with krew.

```
brice@brice-virtual-machine:~/Desktop$ kubectl konfig import -s kubeconfig-us-east-1kubectl
error: write /dev/stdout: permission denied
```

However, running kubectl konfig does not produce this issue. Since `kubectl konfig` version does not seem to be a command, i cannot provide that detail, however my environment is ubuntu with the following `kubectl version` output:

`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-16T02:43:21Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
`

Here's the debug output

```+ set -eEuo pipefail
+ TMPFILES=()
+ declare -a TMPFILES
+ trap cleanup EXIT
+ main import -s kubeconfig-us-east-1kubectl krew
+ hash kubectl
+ KUBECTL=kubectl
+ [[ 4 -eq 0 ]]
+ case "$1" in
+ import_ctx -s kubeconfig-us-east-1kubectl krew
+ tmpcfgs=()
+ declare -a tmpcfgs
+ local tmpcfg
+ local tmpinputcfg=
+ local out=
+ local arg=
++ mktemp konfig_XXXXXX
+ tmpcfg=konfig_rj3LF8
+ TMPFILES+=("$tmpcfg")
+ tmpcfgs+=("$tmpcfg")
+ for OPT in "$@"
+ case $OPT in
+ out=/home/brice/.kube/config
+ shift
+ for OPT in "$@"
+ case $OPT in
+ for OPT in "$@"
+ case $OPT in
+ kubectl config view --raw
error: write /dev/stdout: permission denied
+ cleanup
+ [[ 1 -gt 0 ]]
+ rm -- konfig_rj3LF8```

**Comment by corneliusweig** [comment]
I guess you're using snap. Then that's a known problem, see #14.
In case I was wrong, please feel free to reopen.

**Comment by Bjohnson131** [comment]
@corneliusweig do you mean snap to install this plugin or snap to install krew? because I used krew to install the plugin.

**Comment by corneliusweig** [comment]
I mean that `kubectl` was installed via snap. I don't understand why that causes this error, but others have  had the same problem.
